name: terraform-validate

on:
  push:
  pull_request:

jobs:
  terraform-validate:
    name: terraform-validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init basic example
        working-directory: examples/basic
        run: terraform init -backend=false

      - name: Terraform validate basic example
        working-directory: examples/basic
        run: terraform validate

      - name: Terraform init private subnet example
        working-directory: examples/private-subnet-with-vpc-endpoints
        run: terraform init -backend=false

      - name: Terraform validate private subnet example
        working-directory: examples/private-subnet-with-vpc-endpoints
        run: terraform validate
